image: ubuntu:22.04

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y build-essential cmake ninja-build

test:
  stage: test
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build
    - cd build
    - ctest --output-on-failure --output-junit test-report.xml
  artifacts:
    when: always
    reports:
      junit: build/test-report.xml
    paths:
      - build/test-report.xml
